run:
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - bodyclose
    - gocritic
    - goimports
    - gosec
    - misspell
    - revive
    - stylecheck
    - unconvert
    - whitespace
    - goconst
    - asciicheck
    - bidichk
    - dupword
    - exportloopref
    - makezero

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  revive:
    rules:
      - name: exported
        arguments:
          - checkPrivateReceivers
      - name: package-comments
        disabled: true
  goconst:
    min-len: 3
    min-occurrences: 3

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
