name: Lint

on:
  push:
    branches: [ main, chore/project-bootstrap ]
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - '.golangci.yml'
      - '.github/workflows/lint.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - '.golangci.yml'
      - '.github/workflows/lint.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  golangci-lint:
    name: Runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for Go files
        id: check_files
        run: |
          if find . -name "*.go" -print -quit | grep -q .; then
            echo "HAS_GO_FILES=true" >> $GITHUB_ENV
          else
            echo "HAS_GO_FILES=false" >> $GITHUB_ENV
          fi

      - name: Set up Go
        if: env.HAS_GO_FILES == 'true'
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Run golangci-lint
        if: env.HAS_GO_FILES == 'true'
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
